### ISSUE TITLE
PyQT4 is obsolete 

### ISSUE THREAD

**Issue by aragubas** [coppolaemilio/Stellar#55]
Since i can't install PyQT4 on my linux mint *packpage not found* i suspect that this is an Obsolte API.

Also, it will be nice to port this project to render with Pygame itself...

I am thinking about making a  port to my Framework made with pygame...

**Comment by coppolaemilio** [comment]
Yes, the repository is abandoned so I won't be updating any dependencies. 
You should check out Godot Engine, it is what I wanted Stellar to be :)

**Comment by aragubas** [comment]
oh, thats sad, it was a good project...

i guess i will make my own "Stellar" with my Pygame's Application Framework the [Taiyou Framework](https://github.com/aragubas/taiyou-framework)
